---
title: "Cluster Analysis of Categorical Data"
author: "Xiaoyi Ma and Robert Long"
date: "4/14/2021"
output:
  pdf_document:
    toc: yes
    toc_depth: 1
  html_document:
    code_folding: hide
    number_sections: true
    toc: yes
    toc_depth: 1
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = "markup", message = F, echo = T)
```


```{r basic, include=F}
# use this function to conveniently load libraries and work smoothly with knitting
# can add quietly=T option to the require() function
loadPkg = function(pkg, character.only = FALSE) { 
  if (!character.only) { pkg <- as.character(substitute(pkg)) }
  pkg <- ifelse(!character.only, as.character(substitute(pkg)) , pkg)  
  if (!require(pkg,character.only=T, quietly =T)) {  install.packages(substitute(pkg),dep=T); if(!require(pkg,character.only=T)) stop("Package not found") } 
}
loadPkg(knitr)

# unload/detact package when done using it
unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```


```{r load_libraries, include=F}
set.seed(17)

loadPkg("ggplot2")
loadPkg("MASS")
loadPkg("klaR")
loadPkg("cba")
loadPkg("factoextra")
loadPkg("cluster")
```


 
```{r load_data}
data <- read.csv("mushrooms.csv")

data[sapply(data, is.character)] <- lapply(data[sapply(data, is.character)], as.factor)

str(data)

x.data <- subset(data, select=-c(veil.type, class))
```

# Distance Matrix 
```{r diss}
samps <- sample(8124, 500)

data.dist <- daisy(x.data[samps,], metric="gower")

gradient.color <- list(low = "steelblue",  high = "white")
fviz_dist(data.dist, 
   gradient = gradient.color,
   order=F,
   show_labels=F)

```

# Ordered Distance Matrix
```{r diss_ord}
gradient.color <- list(low = "steelblue",  high = "white")
fviz_dist(data.dist, 
   gradient = gradient.color,
   order=T,
   show_labels=F)

```


# k-means Clustering by One-Hot

```{r kmeans, results='markup'}
data.matrix <- model.matrix(~.-1, data=x.data)

fit.kmean = kmeans(data.matrix, 2, iter.max = 15) 

result.kmean.mm <- table(data$class, fit.kmean$cluster)
result.kmean.mm

purity.kmean <- sum(apply(result.kmean.mm, 2, max)) / nrow(x.data)

fviz_cluster(fit.kmean, data.matrix, repel=T)
```

Purity: `r purity.kmean`




# k-means Clustering by Gower

```{r kmeans_gower, results='markup'}

fit.kmean_gower = kmeans(data.dist, 2) 

result.kmean_gower <- table(data[samps, ]$class, fit.kmean_gower$cluster)
result.kmean_gower

purity.kmean_gower <- sum(apply(result.kmean_gower, 2, max)) / 500

fviz_cluster(fit.kmean_gower, data.dist,  repel=T)
```
Purity: `r purity.kmean_gower`


# PAM with One-Hot

```{r pam, results="markup"}

fit.pam <- pam(data.matrix, 2)

result.pam.mm <- table(data$class, fit.pam$clustering)
result.pam.mm

purity.pam <- sum(apply(result.pam.mm, 2, max)) / 8124

fviz_cluster(fit.pam, repel=T)
```

Purity: `r purity.pam`

# PAM with Raw Data
```{r pam_raw, results="markup"}

fit.pam_raw <- pam(x.data, 2)

result.pam_raw.mm <- table(data$class, fit.pam_raw$clustering)
result.pam_raw.mm

purity.pam_raw <- sum(apply(result.pam_raw.mm, 2, max)) / 8124
  
fviz_cluster(fit.pam_raw, repel=T)
```
Purity: `r purity.pam_raw`

# PAM with Gower 
```{r pam_g, results="markup"}
fit.pam_g <- pam(data.dist, 2)

result.pam_g.mm <- table(data[samps, ]$class, fit.pam_g$clustering)
result.pam_g.mm

purity.pam_g <- sum(apply(result.pam_g.mm, 2, max)) / 500

```

Purity: `r purity.pam_g`

## PAM with Gower: MDS and Clusters

```{r pam_mds_g, results='markup'}
pam.mds <- as.data.frame(cmdscale(data.dist,2))

pam.mds$cluster <- as.factor(fit.pam_g$clustering)

ggplot(pam.mds,
       aes(x=V1, y=V2, color=cluster)) + 
  geom_point() + 
  labs(title="MDS Plot for Mushroom Clusters",
       subtitle="Colored by PAM cluster") +
  scale_color_brewer(palette="Set1")
```

## PAM with Raw Data: MDS and Clusters

```{r pam_mds_raw, results='markup'}
pam.mds <- as.data.frame(cmdscale(data.dist,2))

pam.mds$cluster <- as.factor(fit.pam_raw$clustering[samps])

ggplot(pam.mds,
       aes(x=V1, y=V2, color=cluster)) + 
  geom_point() + 
  labs(title="MDS Plot for Mushroom Clusters",
       subtitle="Colored by PAM cluster") +
  scale_color_brewer(palette="Set1")
```

# PAM Results

```{r vars_by_cluster, results='markup'}

pam.cluster <- fit.pam$clustering

data.fused <- cbind(data, pam.cluster)

ggplot(data.fused) +
  geom_bar(aes(x=cap.shape, fill=factor(pam.cluster)), position="dodge") + 
  xlab("Cap Shape") +
  ylab("Count") 
  

```



```{r unload_libraries, include=F}

unloadPkg(klaR)
unloadPkg(cba)
unloadPkg(factoextra)
unloadPkg(cluster)
unloadPkg(MASS)
unloadPkg(ggplot2)
```

